/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hd_earth.glb -o app/components/models/Earth.tsx --types 
Author: klaus018579 (https://sketchfab.com/klaus018579)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hd-earth-f3134609078c4719a943cfe77a7af6f6
Title: HD Earth
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere_Material001_0: THREE.Mesh
    Sphere001_Material002_0: THREE.Mesh
    Sphere002_Material003_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/hd_earth.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Sphere_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Sphere001_Material002_0.geometry} material={materials['Material.002']} rotation={[2.676, 0.901, 2.684]} scale={100.822} />
        <mesh geometry={nodes.Sphere002_Material003_0.geometry} material={materials['Material.003']} rotation={[0.013, -1.015, -2.029]} scale={101.228} />
      </group>
    </group>
  )
}

useGLTF.preload('/hd_earth.glb')
